###
### Pipeline que realiza a identificação das configurações para os demais pipeline
###

name: Identifier
on:
  workflow_call:
    inputs:
      github_ref_name:
        required: true
        type: string
      github_event_name:
        required: true
        type: string
      github_base_ref:
        required: true
        type: string
      app_name:
        required: true
        type: string
    outputs:
      environment_name:
        description: "Environment name according to the branch"
        value: ${{ jobs.extr-info.outputs.environment_name }}
      github_env_file_field:
        description: "Name da variable environment field github"
        value: ${{ jobs.extr-info.outputs.github_env_file_field }}
jobs:
  extr-info:
    name: Name Environment
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{inputs.github_ref_name}}
      BRANCH_NAME_REF: ${{inputs.github_base_ref}}
      EVENT_TYPE: ${{inputs.github_event_name}}
      ENV_NAME: ""
      GITHUB_ENV_FILE_FIELD: ${{inputs.app_name}}_DEVELOPMENT_ENV
      APP_NAME: ${{inputs.app_name}}_
    outputs:
      environment_name: ${{ steps.name.outputs.environment_name }}
      github_env_file_field: ${{ steps.name_file_env.outputs.name_file_env }}
    steps:
      - name: Verify type Event Branch Target
        if: contains(env.EVENT_TYPE, 'pull_request')
        run: echo "BRANCH_NAME=${{ env.BRANCH_NAME_REF }} " >> $GITHUB_ENV
      - name: Environment Production
        if: contains(env.BRANCH_NAME, 'main') || contains(env.BRANCH_NAME, 'hotflix') && contains(env.EVENT_TYPE, 'push')
        run: |
          echo "GITHUB_ENV_FILE_FIELD=PRODUCTION_ENV" >> $GITHUB_ENV
          echo "ENV_NAME=production" >> $GITHUB_ENV
      - name: Environment Staging
        if: contains(env.BRANCH_NAME, 'main') || contains(env.BRANCH_NAME, 'hotflix') && contains(env.EVENT_TYPE, 'pull_request')
        run: |
          echo "GITHUB_ENV_FILE_FIELD=STAGING_ENV" >> $GITHUB_ENV
          echo "ENV_NAME=staging" >> $GITHUB_ENV
      - name: Environment Homologation
        if: startsWith(env.BRANCH_NAME, 'release') && contains(env.EVENT_TYPE, 'pull_request')
        run: | 
          echo "GITHUB_ENV_FILE_FIELD=HOMOLOGATION_ENV" >> $GITHUB_ENV
          echo "ENV_NAME=homologation" >> $GITHUB_ENV
      - name: Environment Development
        if: contains(env.BRANCH_NAME, 'develop') && contains(env.EVENT_TYPE, 'pull_request')
        run: echo "ENV_NAME=development" >> $GITHUB_ENV
      - name: Defined Environment
        id: name
        run: echo "environment_name=${{ env.ENV_NAME }}" >> $GITHUB_OUTPUT
      - name: Defined Name File Environment
        id: name_file_env
        run: echo "name_file_env=${{env.APP_NAME}}${{ env.GITHUB_ENV_FILE_FIELD }}" >> $GITHUB_OUTPUT